Created database at ./tmp/databases.

###HOLOCHAIN_SETUP###
###ADMIN_PORT:4444###
###HOLOCHAIN_SETUP_END###
Conductor ready.
[2mOct 01 13:43:14.893[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:28 Running Validation...
[2mOct 01 13:43:14.893[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:37 Validation successful...
[2mOct 01 13:43:15.443[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:28 Running Validation...
[2mOct 01 13:43:15.443[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:37 Validation successful...
[2mOct 01 13:43:15.466[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:28 Running Validation...
[2mOct 01 13:43:15.467[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:37 Validation successful...
[2mOct 01 13:43:15.468[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:28 Running Validation...
[2mOct 01 13:43:15.468[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:37 Validation successful...
[2mOct 01 13:43:15.631[0m [31mERROR[0m holochain::conductor::conductor: error dispatching network event error=KeystoreError(LairError(Other(OtherError("unexpected: ErrorResponse { msg_id: 26, message: \"Failed to fulfill hosted signing request: 'purposeful signing error'\" }"))))
[2mOct 01 13:43:15.740[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:28 Running Validation...
[2mOct 01 13:43:15.740[0m [34mDEBUG[0m [1mwasm_trace[0m: test:zomes/test/src/lib.rs:37 Validation successful...
[2mOct 01 13:43:15.764[0m [31mERROR[0m holochain::conductor::conductor: error dispatching network event error=KeystoreError(LairError(Other(OtherError("unexpected: ErrorResponse { msg_id: 30, message: \"Failed to fulfill hosted signing request: 'purposeful signing error'\" }"))))
